---
deployment:
  tasks:
    - export DEPLOYPATH=/home/khandesh21at/public_html/familytree
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R googlemaps $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R include $DEPLOYPATH
    - /bin/cp -R languages $DEPLOYPATH
    - /bin/cp -R media $DEPLOYPATH
    - /bin/cp -R styles $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp -R views $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp gendex.php $DEPLOYPATH
    - /bin/cp gezin.php $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp sitemap.php $DEPLOYPATH
