display_errors = Off
post_max_size = 50M
upload_max_filesize = 49M
max_input_vars = 4000
error_reporting = E_ALL
extension_dir = "C:\Users\faishai\Appdata\Local\Microsoft\WinGet\Packages\PHP.PHP.8.4_Microsoft.Winget.Source_8wekyb3d8bbwe\ext"
extension = pdo_mysql
extension = mysqli
error_log = "C:\Users\faishai\familytree"
